library(dplyr)
library(ggplot2)
dataplot1 <- read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors = FALSE,dec=".")
subsetdata <- dataplot1[dataplot1$Date %in% c("1/2/2007","2/2/2007"),]
activepower <- as.numeric(subsetdata$Global_active_power)
dateandtime <- strptime(paste(subsetdata$Date, subsetdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
submetering1<-as.numeric(subsetdata$Sub_metering_1)
submetering2<-as.numeric(subsetdata$Sub_metering_2)
submetering3<-as.numeric(subsetdata$Sub_metering_3)
png("plot3.png",width=480,height=480)
plot(dateandtime, submetering1, type="l", xlab="", ylab="Energy submetering")
lines(dateandtime, submetering2,col="red")
lines(dateandtime,submetering3,col="blue")
legend("topright",c("sub_metering_1","sub_metering_2","sub_metering_3"),lty=1,lwd=2.5,col=c("black","red","blue"))
dev.off()

